#!/bin/sh

exec gnutls-serv --x509cafile ../examples/certs/ca.pem \
                 --x509keyfile ../examples/certs/valid.key \
                 --x509certfile ../examples/certs/valid.crt \
                 --quiet --port 10000

